# Generated by Django 5.2.1 on 2025-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Eggs', 'Eggs'), ('Chicks', 'Chicks'), ('Chicken', 'Chicken')], max_length=50)),
                ('subcategory', models.CharField(blank=True, choices=[('Broilers', 'Broilers'), ('Layers', 'Layers')], max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
