# Generated by Django 5.2.13 on 2026-05-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('eggs_tray', 'Eggs (tray)'), ('eggs_half_tray', 'Eggs (half tray)'), ('broiler_chicken', 'Broiler chicken'), ('layer_chicken', 'Layer chicken'), ('manure_bags', 'Manure (bags)'), ('manure_bulk', 'Manure (bulk)'), ('feed_starter', 'Feed (starter)'), ('feed_grower', 'Feed (grower)'), ('feed_finisher', 'Feed (finisher)')], default='eggs_tray', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='Products.product')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
